AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.
Resources:
  hinditexttospeech:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./
      Handler: main.lambda_handler
      Runtime: python3.8